config/routes.rb
Rails.application.routes.draw do
  devise_for :members, controllers: { sessions: 'members/sessions' }
  
 # namespace :admin do
  #resources :members

 
  root 'pages#home'
  #get '/login', to: 'sessions#new'
  #post '/login', to: 'sessions#create'
  #delete 'logout', to: 'sessions#destroy'
  

  #devise_for :members
  resources :discussions
end

app/models/answer.rb
class Answer < ApplicationRecord
 has_many :likes, as: :likeable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
 has_many :likes, as: :likeable
end

app/models/discussion.rb
class Discussion < ApplicationRecord
 has_many :likes, as: :likeable
 belongs_to :member, optional: true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :likeable, polymorphic: true
end

app/models/member.rb
class Member < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/discussions_controller.rb
class DiscussionsController < ApplicationController
  def index
    @discussions = Discussion.all
  end
  
  def show
    @discussion = Discussion.find(params[:id])
  end
  
  def new
    @discussion = Discussion.new
  end
  
  def create
    discussion = Discussion.new(discussion_params)
    discussion.save!
    redirect_to discussions_url, notice: "ディスカッションテーマ「#{discussion.theme}」を登録しました。"
  end
  
  def edit
    @discussion = Discussion.find(params[:id])
  end
  
  def update 
    discussion = Discussion.find(params[:id])
    discussion.update!(discussion_params)
    redirect_to discussions_url, notice: "ディスカッションテーマ「#{discussion.theme}」を更新しました。"
  end
  
  def destroy
    discussion = current_member.discussions.find(params[:id])
    discussion.destroy
    redirect_to discussions_url, notice: "ディスカッションテーマ「#{discussion.theme}」を削除しました。"
  end
  
private
  def discussion_params
    params.require(:discussion).permit(:theme, :description)
  end
end

app/controllers/members/confirmations_controller.rb
# frozen_string_literal: true

class Members::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/members/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Members::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/members/passwords_controller.rb
# frozen_string_literal: true

class Members::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/members/registrations_controller.rb
# frozen_string_literal: true

class Members::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/members/sessions_controller.rb
# frozen_string_literal: true

class Members::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  protected
    def after_sign_in_path_for(resource)
      discussions_path
    end
    
  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/members/unlocks_controller.rb
# frozen_string_literal: true

class Members::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
        
    end
end

app/helpers/admin/members_helper.rb
module Admin::MembersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/discussions_helper.rb
module DiscussionsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/discussions/edit.html.slim
h1 Discussions#edit
p Find me in app/views/discussions/edit.html.slim
.nav.jsutify-content-end
= link_to '一覧', discussions_path, class:'nav-link'

= form_with model: @discussion, local: true do |f| 
 .form-group
 = f.label :theme
 = f.text_field :theme, class: 'form-control', id: 'discussion_theme' 

 .form-gruop 
 = f.label :description
 = f.text_area :description, rows: 5, class: 'form-control', id: 'discussion_description'
 .form-action
 = f.submit nil, class: 'btn btn-primary' 

app/views/discussions/index.html.slim
h1 Discussions#index
p Find me in app/views/discussions/index.html.slim
= link_to '新規登録', new_discussion_path, class: 'btn btn-primary'
= button_to 'ログアウト', destroy_member_session_path, method: :delete
.mb-3
table.table.table-hover
  thead.thead-default
    tr 
      th = Discussion.human_attribute_name(:theme)
      th = Discussion.human_attribute_name(:created_at)
      th
  tbody

app/views/discussions/new.html.slim
h1 Discussions#new
p Find me in app/views/discussions/new.html.slim
.nav.jsutify-content-end
= link_to '一覧', discussions_path, class:'nav-link'

= form_with model: @discussion, local: true do |f| 
 .form-group
 = f.label :theme
 = f.text_field :theme, class: 'form-control', id: 'discussion_theme' 

 .form-gruop 
 = f.label :description 
 = f.text_area :description, rows: 5, class: 'form-control', id: 'discussion_description' 
 .form-action
 = f.submit nil, class: 'btn btn-primary' 

app/views/discussions/show.html.slim
h1 Discussions#show
p Find me in app/views/discussions/show.html.slim
.nav.justify-content-end
= link_to '一覧', discussions_path, class: 'nav-link'
= link_to '編集', edit_discussion_path, class: 'btn btn-@primary mr-3'
= link_to '削除', @discussion, method: :delete, data: { confirm: "タスク「#{@discussion.theme}」を削除します。よろしいですか？" }, class: 'btn btn-danger'
table.table.table-hover
 tbody
   tr
     th = Discussion.human_attribute_name(:id)
     td = @discussion.id
   tr
     th = Discussion.human_attribute_name(:theme)
     td = @discussion.theme
   tr
     th = Discussion.human_attribute_name(:description)
     td = simple_format(h(@discussion.description),{}, sanitize:false, wrapper_tag: "div")
   tr         
     th = Discussion.human_attribute_name(:created_at)
     td = @discussion.created_at
   tr         
     th = Discussion.human_attribute_name(:updated_at)
     td = @discussion.updated_at

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Community
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    link[rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous"]
  body
    main
      .container
        = yield
    script[src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"]
    script[src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"]
    script[src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"]

app/views/pages/home.html.slim
p 'このページは仮のトップページです'
= link_to '一覧', discussions_path, class:'nav-link'